apiVersion: apps/v1
kind: Deployment
metadata: 
  name: platform-depl
spec:
  replicas: 3 #number of instance for scaling
  selector: 
    matchLabels: 
      app: platformservice
  template: 
    metadata: 
      labels: 
        app: platformservice
    spec:
      containers: 
        - name: platformservice
          image: fbicsharp/platformservice:latest #dockerhub image


# TESTING AND EXLLANING  SCRIPT 
#1.(lunch deployment) kubectl apply -f platform-depl.yaml
#2.(retive the deployment) kubectl get deployments 
# in this case I configured 3 instances
# NAME            READY   UP-TO-DATE   AVAILABLE   AGE
# platform-depl   3/3     3            3           40m
#3.(get the pod ) kubectl get pod
# Note the is 3 instances under cration when creation il complate thy comes "Running"
# NAME                             READY   STATUS              RESTARTS   AGE
# platform-depl-587675c5b9-2phhm   0/1     ContainerCreating   0          3s
# platform-depl-587675c5b9-tgbt7   0/1     ContainerCreating   0          3s
# platform-depl-587675c5b9-x62pd   0/1     ContainerCreating   0          3s
#if you remove a pod they will be recreated automatically
#4.(delete the deployment by name) kubectl delete deployment platform-depl

